import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:iconify_flutter/iconify_flutter.dart';
import 'package:iconify_flutter/icons/ph.dart';
import 'package:salintinig/pages/parent/parent_announcements_page.dart';

class ParentPhilIriAssessmentPage extends StatelessWidget {
  const ParentPhilIriAssessmentPage({super.key});
  static const _blue = Color(0xFF1B64D8);
  @override
  Widget build(BuildContext context) => Scaffold(backgroundColor: const Color(0xFFFCFAF7), drawer: buildParentSidebarDrawer(context, activeIndex: 1), appBar: AppBar(backgroundColor: const Color(0xFFFCFAF7), elevation: 0, leading: Builder(builder: (c) => IconButton(onPressed: () => Scaffold.of(c).openDrawer(), icon: Iconify(Ph.list, color: Colors.black, size: 28))), title: Text('Phil-IRI Assessment', style: GoogleFonts.inter(fontSize: 17, fontWeight: FontWeight.w800, color: Colors.black)), centerTitle: true), body: SingleChildScrollView(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: double.infinity, padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: _blue, borderRadius: BorderRadius.circular(20)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Assessment Results', style: GoogleFonts.inter(color: Colors.white, fontWeight: FontWeight.w700)), const SizedBox(height: 14), Text('Phil-IRI Reading Profile', style: GoogleFonts.inter(color: Colors.white, fontSize: 21, fontWeight: FontWeight.w900)), const SizedBox(height: 5), Text('Review teacher-recorded results and reading levels.', style: GoogleFonts.inter(color: Colors.white, fontSize: 12))])), const SizedBox(height: 20), Text('Latest Assessment', style: GoogleFonts.inter(fontSize: 16, fontWeight: FontWeight.w800)), const SizedBox(height: 10), Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16), border: Border.all(color: const Color(0xFFE2E8F0))), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Reading Level', style: GoogleFonts.inter(fontSize: 11, color: const Color(0xFF64748B))), Text('Instructional', style: GoogleFonts.inter(fontWeight: FontWeight.w800, color: const Color(0xFFD97706)))]), Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Text('Assessment', style: GoogleFonts.inter(fontSize: 11, color: const Color(0xFF64748B))), Text('Post-Test', style: GoogleFonts.inter(fontWeight: FontWeight.w800, color: _blue))])])), const SizedBox(height: 24), Text('Phil-IRI Test History', style: GoogleFonts.inter(fontSize: 16, fontWeight: FontWeight.w800)), const SizedBox(height: 10), _card('GST Post-Test (Form 1A)', 'July 24, 2026', 'Instructional', '82 WPM • 88.5% oral accuracy'), const SizedBox(height: 10), _card('GST Pre-Test (Form 1A)', 'June 10, 2026', 'Frustrational', '77 WPM • 81.0% oral accuracy')])));
  Widget _card(String title,String date,String level,String stats) => Container(padding: const EdgeInsets.all(15), decoration: BoxDecoration(color: Colors.white,borderRadius: BorderRadius.circular(16),border: Border.all(color: const Color(0xFFE2E8F0))), child: Column(crossAxisAlignment: CrossAxisAlignment.start,children:[Text(title,style:GoogleFonts.inter(fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(date,style:GoogleFonts.inter(fontSize:11,color:const Color(0xFF64748B))),const SizedBox(height:6),Text('$level • $stats',style:GoogleFonts.inter(fontSize:12,fontWeight:FontWeight.w700))]));
}
